%%% DATA INPUT

%% Controller values
Gs=1; % Sensor Gain
Ga=3; % Actuator
Gr=1; % Prefilter ( reference generator )
Gd=1; % Plant disturbance

Kd=2; % Proportion between input and output

%% Create signal input structs
% coefficient: signal input value
% maxError: max output error
% type: 0 for none, 1 for polynomial, 2 for sinusoidal
% frequency: only for sinusoidal signals in rad/sec. 0 for all others
% order: only for polynomial signals. -10 for all others
% tf: equal to input signal transfer function or gain block
% on: must always be initialized to 1

r= struct('coefficient', 1 ...
        , 'maxError', 1.5*10^(-1) ...
        , 'actualError', -1000 ...
        , 'type', 1 ...
        , 'frequency', 0 ...
        , 'order', 0 ...% SHOULD BE 0
        , 'tf', Gr ...
        , 'on', 1 ...
        );
da= struct('coefficient', 8.5*10^(-3) ...
        , 'maxError', 25*10^(-3) ...
        , 'actualError', -1000 ...
        , 'type', 1 ...
        , 'frequency', 0 ...
        , 'order', 0 ... % SHOULD BE 0
        , 'tf', 1 ...
        , 'on', 1 ...
        );
dp= struct('coefficient', 6*10^(-2) ...
        , 'maxError', 6*10^(-4) ...
        , 'actualError', -1000 ...
        , 'type', 2 ...
        , 'frequency', 10 ...
        , 'order', -10 ...
        , 'tf', Gd ...
        , 'on', 1 ...
        );
ds= struct('coefficient', 1*10^(-3) ...
        , 'maxError', 1*10^(-4) ...
        , 'actualError', -1000 ...
        , 'type', 2 ...
        , 'frequency', 10000 ...
        , 'order', -10 ...
        , 'tf', 1 ...
        , 'on', 1 ...
        );

%% Time-Domain Performance Specifications

riseTime.on=1;
riseTime.maxValue=5e-3;

overshoot.on=1;
overshoot.maxValue=0.08;

settlingTime.on=0;
settlingTime.maxValue=12;
settlingTime.tolerance=0.05;

%% Plant Values

Gp.nCoefficients=2;
Gp.nOriginPoles=1;
Gp.inputString='(10e6*coeff1)/((s^2 + coeff2*s))'; % ORIG
% Gp.inputString='s^5*(10e6*coeff1)/((s + coeff2))'; % WRONG
Gp.coefficient(1)=struct('low', 0.8 ...
                ,'high', 1.2 );
Gp.coefficient(2)=struct('low', 420 ...
                ,'high', 580 );
            


